[features]
seeds = false
[programs.localnet]
auction = "5FXmbT3CoPP1LGesbtN9AC51QUx8jSjxSwMjgor6rmua"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/strogiyotec/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
